-- Seed data generated from questions.json

TRUNCATE TABLE questions, courses CASCADE;

INSERT INTO courses (id, title, code) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Chemistry_of_Natural_Product(CNP)', 'CNP-101');

INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.3. Chirality … Exercise : Among the natural products shown below, which are chiral and which are achiral?  Give the number of  stereocenters  in each case.', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide34.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.5. Naming enantiomers… Groups tied? Example:', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide44.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.6. Optical activity … Example: A solution of (+)- alanine  from a fossil exhibits a value of [α] = 4.25.  What is its  ee  and optical purity?  What is the actual enantiomer composition of the sample, and how is the measured optical rotation derived from it?  The specific rotation of pure (+)- alanine  is + 8.5', NULL, 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.7. Resolution… Resolution The separation of a racemic mixture into its  enantiomeric  components How?  Reaction with pure enantiomer Enzymes  Chiral chromatography', NULL, 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.7.2. Isomers with… Molecules with many  stereocenters How many  stereocenters  cholesterol has?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide81.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.7.2. Isomers with… For a molecule with n  sterocenters           2 n   stereoisomers  (not always. Why?) Example: 2-Bromo-3-chlorobutane 2  stereocenters 2 2  = 4  stereoisomers', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide82.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.8. Meso… Meso compounds  Compounds that are achiral, yet contain chirality centers How to check? Plane of symmetry? Best example: tartaric acid two  stereocenters ; 4  stereoisomers  ????', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide87.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.8. Meso… Why only three?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide88.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.8. Meso… But the 2R,3S and 2S, 3R really enantiomers?  No!!!!', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide89.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '1.10. Biological… Why do enantiomers have different biological properties?  Most of the molecules that make up living organisms are chiral', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_1-Stereochemistry_slide96.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Exercise   Classify the following monosaccharides:', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide13.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Why is the  β   anomer  of  glucopyranose  in higher amount than α  anomer ?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide33.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Exercise: Calculating specific rotations of  diastereomeric  sugar mixtures Question: Calculate how much of the α ([α] = + 112.2°)  anomer  and how much of the β ([α] = + 18.7°)  anomer  are present in an equilibrium mixture with a specific rotation of + 52.7°.', NULL, 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Ketoses   Two  alditols . Why?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide49.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Exercise What products are obtained from the reduction of', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide50.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Only oxidize only those containing aldehyde functional group.  Why, then, ketoses give positive test?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide56.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Exercise Predict the degradation products of fructose', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide63.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Exercise What monosaccharides form the same  osazone  as D- sorbose ?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide74.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Exercise : What monosaccharides would be formed in a  Kiliani –Fischer synthesis starting with D- xylose ?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide79.png', 'OPEN', now());
INSERT INTO questions (course_id, content, image_url, question_type, created_at) VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Disaccharides   glycosides formed from two  monosacharides   Connected by  glycosidic  linkages So, what are glycosides?', '/course-images/Chemistry_of_Natural_Product(CNP)_Chapter_2-Carbohydrates_slide83.png', 'OPEN', now());
